name: be_chill
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0

  cupertino_icons: ^1.0.6
  
  google_fonts: ^6.2.0

  country_picker: ^2.0.25

  flutter_staggered_grid_view: ^0.7.0

  cloud_firestore: ^4.15.6
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  firebase_storage: ^11.6.7
  
  mask_text_input_formatter: ^2.9.0
  
  provider: ^6.1.2
  
  pinput: ^4.0.0
  
  shared_preferences: ^2.2.2
  
  image_picker: ^1.0.7
  transparent_image: ^2.0.1

  flutter_localizations:
    sdk: flutter
  image_cropper: ^5.0.1
  fast_contacts: ^3.1.3
  insta_assets_picker: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/